### PR TITLE
Rewrite pothos extractor in babel

### PR DESCRIPTION
**Pull request by Mokshit06**
This PR ports the pothos schema extractor over to babel. This also fixes the issue with the acorn extractor where the references used wouldn't get extracted, but since babel tracks bindings this now works. I've also added a vitest test to ensure that the output is correct and it matches the one produced by the acorn extractor.

### CODE REVIEW

**Comment by RobbeCl** [comment]
Im curious if this will get merged soon :-)

**Comment by JakeHL** [comment]
Looking forward to this being merged. @Mokshit06 Could you suggest a workaround for the meantime?

**Comment by thdxr** [comment]
I'm including this in sst 2.0

**Comment by michelts** [comment]
I believe this ticket can be closed now, can't it?

**Pull request closed without merging**
