### PR TITLE
[Examples]: Update bucket image resize with latest aws sdk

### PR DESCRIPTION
**Pull request by tranlehaiquan**
Update example Bucket image resizes with latest AWS SDK version 3.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks! I'll make a note to test this and merge it.

**Comment by tranlehaiquan** [comment]
Hi @jayair 
Please also update the tutorial page here https://sst.dev/examples/how-to-automatically-resize-images-with-serverless.html
Sorry I can't page the source page to update.

**Comment by jayair** [comment]
Would appreciate an edit there as well. Click the Edit this page button under the page title?

**Comment by tranlehaiquan** [comment]
Hi @jayair 
Updated here https://github.com/AnomalyInnovations/serverless-stack-com/pull/720

**Comment by jayair** [comment]
Perfect! Appreciate it!

**Pull request merged**
