### PR TITLE
support nodejs18.x runtime

### PR DESCRIPTION
**Pull request by Newbie012**
closes https://github.com/serverless-stack/sst/issues/2212

[AWS Lambda has added support for Node.js 18](https://aws.amazon.com/about-aws/whats-new/2022/11/aws-lambda-support-node-js-18/) and aws-cdk-lib has exposed [lambda.Runtime.NODEJS_18_X](https://github.com/aws/aws-cdk/commit/176feefd7ceb4e8dc622283e2b40cab306705580)

This PR exposes nodejs18.x.

### CODE REVIEW

**Comment by Newbie012** [comment]
Hi @fwang, I'm hoping it's okay to tag you here, Is there a blocker for this PR to be merged? If so, I'll be happy to contribute where necessary.

**Comment by adolfogc** [comment]
Would be cool if `nodejs18.x` be also available in `sst2`.

BTW, @Newbie012, version `2.53.0` of `aws-cdk-lib` is now the latest.

**Comment by Rajivhost** [comment]
Hi all,

any updates on this please @thdxr @fwang ?

**Comment by Rajivhost** [comment]
Hi @Newbie012,

Seems like there are conflicts

image

**Comment by Newbie012** [comment]
@Rajivhost I stopped updating the PR since it conflicts whenever a new version is published. I will update this PR once it'll be approved by one of the maintainers 🙂.

**Comment by oyed** [comment]
@fwang Sounds awesome - any clues on to when an SST2 RC will be publicly available? NodeJS 18 LTS + PNPM support are pretty huge for us :)

**Comment by Newbie012** [comment]
It might be a bit off-topic, but what's the problem of using pnpm in sst1? This is my current setup and it seems to work pretty nicely

**Comment by Rajivhost** [comment]
> @fwang Sounds awesome - any clues on to when an SST2 RC will be publicly available? NodeJS 18 LTS + PNPM support are pretty huge for us :)

Hi @oyed, I'm also using PNPM on my projects with sstv1 and don't have problem.

**Comment by khuezy** [comment]
Any problems updating to the latest version `2.53.0`?

**Comment by revmischa** [comment]
> Any problems updating to the latest version `2.53.0`?

`2.55.0` now 😄

**Comment by fwang** [comment]
Thanks @Newbie012! I just updated CDK to 2.55.0 and manually merged the PR into the `sst2` branch.

If you are already using SST v2, the latest `sst@snapshot` release has both.

If you want to give SST v2 a try, we will have an official release candidate next week.

**Comment by revmischa** [comment]
@fwang could we possibly get this one cherry-picked to 1.x as well? it would really help me out

**Comment by revmischa** [comment]
> It might be a bit off-topic, but what's the problem of using pnpm in sst1? This is my current setup and it seems to work pretty nicely

How are you doing this? I get this error:
```
Error: The specified runtime is not supported for sst.Function. Only NodeJS, Python, Go, and .NET runtimes are currently supported.
```

**Comment by davidrhoderick** [comment]
> @fwang could we possibly get this one cherry-picked to 1.x as well? it would really help me out

I too would like it moved to version 1.x.  I tried updating my project today to SST2 and I just couldn't get it working.  I'd rather just be able to use 18 on the old project until SST2 is ready for launch and this is a blocker at the moment.

**Comment by jayair** [comment]
@fwang is there a workaround for this for 1.x?

**Comment by khuezy** [comment]
Frank posted a comment on [discord](https://discord.com/channels/983865673656705025/983865673656705028/1055208929812025476):

```
const oldRunDeferredBuilds = app.runDeferredBuilds();
app.runDeferredBuilds = async () => {
  await oldRunDeferredBuilds();

  // loop through app's children
  // if child instanceof lambda.Function
  // const cfnFunction = child.node.defaultChild as lambda.CfnFunction
  // cfnFunction.runtime = "nodejs18.x"
}
```

**Comment by davidrhoderick** [comment]
I'm not really sure how this is implemented, does anyone have an example?  Here's what's unclear:

1. Where does this run?  In the `index.ts` default function?
2. Where in the `index.ts` does this run?  Before or after the `app.stack(...)...` (or does it even matter)?
3. I tried `app.children` but that's undefined.  Where does one get `app.children`?  (This would be the first time for me reading that an SST `app` has `children` as opposed to stacks...)
4. Am I importing `lambda.Function` from `aws-lambda`?

I'll try and bumble my way through it but I don't think this is a work-around without showing how it's actually implemented in some way.

**Comment by soflass1293** [comment]
Hello,
Is there currently any way to upgrade the runtime to `"nodejs18.x"` in SST v1?

Thank you.

**Comment by allanhortle** [comment]
I found a pretty decent hack was to use a [cdk Aspect](https://docs.aws.amazon.com/cdk/v2/guide/aspects.html) to iterate through the stack looking for `CfnFunctions` and mutating their runtime prop. @davidrhoderick 

```ts
export default function (app: App) {
    app.setDefaultFunctionProps((stack) => {
        Aspects.of(stack).add({
            visit: (node) => {
                if (node instanceof CfnFunction) {
                    if (node.runtime?.includes('nodejs')) node.runtime = 'nodejs18.x';
                }
            }
        });
        return {
            // rest of the default props.
        };
    });
}
```

**Pull request closed without merging**
