### PR TITLE
[Example] How to use lambda layers in your serverless

### PR DESCRIPTION
**Pull request by tranlehaiquan**
Includes:

- Change to node 18 because AWS layer in ESM has some issues in NODE 14, 16. [Here](https://repost.aws/questions/QUkqtaCZBNTguN6qr5Oj2hpg/node-js-module-not-found-using-es-import-with-lambda-layers) , [here](https://github.com/aws/aws-sdk-js-v3/issues/3230#issuecomment-1561973247)
- Change from chrome-aws-lambda to @sparticuz/chromium
- Test passed with sst dev
- Test passed after sst deploy

image

### CODE REVIEW

**Comment by tranlehaiquan** [comment]
Update document: https://github.com/AnomalyInnovations/serverless-stack-com/pull/722

**Comment by jayair** [comment]
Link to Discord thread https://discord.com/channels/983865673656705025/1115969381323784344/1126217740856856606

**Comment by jayair** [comment]
Thanks again for this @tranlehaiquan 

I should've mentioned that these examples are generated from a template. Here's the source for it: https://github.com/serverless-stack/sst/tree/master/packages/create-sst/bin/presets/examples/layer-chrome-aws-lambda

Can you update these files in the template instead? If not let me know and I'll do them.

**Comment by jayair** [comment]
Thanks again!

**Comment by tranlehaiquan** [comment]
Hi @jayair 
I updated the create-sst template, but not sure how to test it. Could you please help test it for me?
Many thanks.

**Comment by jayair** [comment]
No worries, this looks good. I'm going to merge it and generate the examples (it takes around half an hour to run), it'll then generate the examples that you can test with the `npx create-sst` CLI.

**Comment by jayair** [comment]
Here's the job: https://github.com/serverless-stack/sst/actions/runs/5526135124 once it's done you can test it

**Pull request merged**
