### PR TITLE
GraphQLHandler: replace graphql-helix with graphql-yoga

### PR DESCRIPTION
**Pull request by michaelgmcd**
GraphQL Helix doesn't seem to be maintained anymore. graphql-yoga is a very powerful server fully capable of running in lambdas. I've been using an implementation almost identical to this for a couple weeks now and it's been working. GraphiQL works as well.

The handler implementation is heavily based on graphql-yoga's documentation:
https://the-guild.dev/graphql/yoga-server/docs/integrations/integration-with-aws-lambda

### CODE REVIEW

**Comment by michaelgmcd** [comment]
Note that this is a breaking change. I left it as WIP since I haven't tested it. What's the best way to test this? I can use this in my own project and confirm the functionality works, but open to other suggestions.

**Comment by thdxr** [comment]
@michaelgmcd using it in your own project makes sense! let me know if you get to a place of confidence and I'll work out a release plan

**Review by Bhavikpatel576 — COMMENTED** [review]
Might be helpful to update the docs as well [here ](https://github.com/serverless-stack/sst/blob/master/www/docs/learn/graphql-api.md) on what input shape is

**Comment by michaelgmcd** [comment]
I've been testing this locally on my project without issues. I think it's good to review!

**Comment by michaelgmcd** [comment]
Working on doc updates now

**Comment by michaelgmcd** [comment]
Updated the docs and checked all the examples. May be worth adding some more complex examples, but each one only passes schema, so they don't need to be updated:
```javascript
export const handler = GraphQLHandler({
  schema,
});
```

**Pull request merged**
