### PR TITLE
fix: prevent overwriting FilterCriteria in Table consumers (#3115)

### PR DESCRIPTION
**Pull request by jonnedeprez**
fix for #3115

### CODE REVIEW

**Comment by jayair** [comment]
Discord thread https://discord.com/channels/983865673656705025/1130869687308259450/1130869687308259450

**Comment by RobbeCl** [comment]
What needs to happen in order to merge this PR?

**Comment by jayair** [comment]
I'll follow up with the team.

**Comment by fwang** [comment]
Thanks @jonnedeprez. Will be in the next release.

**Pull request merged**
