### PR TITLE
`Continue` -> `Return`

### LINKED ISSUE #3011: Remix project selecting NO for drop-in mode gives error
```
? You are in a Remix project so SST will be setup in drop-in mode. Continue? No
file:///Users/mauscoelho/.npm/_npx/2f33f932f9789c0f/node_modules/create-sst/bin/create-sst.mjs:21
    const [preset, name, destination] = await (async function () {
                                        ^

TypeError: (intermediate value) is not iterable
    at Command.<anonymous> (file:///Users/mauscoelho/.npm/_npx/2f33f932f9789c0f/node_modules/create-sst/bin/create-sst.mjs:21:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

### PR DESCRIPTION
**Pull request by Rohithgilla12**
I think it fixes #3011 

I wasn't able to confirm the fix, I am not sure how to run it locally so couldn't verify the fix.

Is there any docs on the dev setup and building the `sst` command and running it locally?

Thanks.

### CODE REVIEW

**Comment by jayair** [comment]
Thanks! For the create-sst CLI it's a little easier. You can simple run `node bin/create-sst.mjs` locally to test. Give it a try?

**Comment by Rohithgilla12** [comment]
@jayair Thanks
I did try it and it's working now!!

image

**Comment by fwang** [comment]
Thanks @Rohithgilla12!

**Comment by jayair** [comment]
@Rohithgilla12 why does it look like Shakespeare wrote your code?

**Pull request merged**
